### ISSUE TITLE
Server location

### ISSUE THREAD

**Issue by ha-seungwon** [EMDC-OS/remote-swap#1]
Depending on the service providers and location of edge servers, storing pages on the network could also lead to monetary (data) cost in addition to latency. Is there any consideration in striking a balance for these?

**Comment by tlsghkrnfla** [comment]
It is also an important factor to consider since it requires the use of additional resources on the edge. However, if a high-capacity, high-performance SSD is used as additional swap space, the cost is unlikely to be a significant concern from the service provider's perspective. Given that network latency is the main bottleneck when fetching data from the edge, using a large-capacity SSD for swap space would offer considerable benefits.
