### ISSUE TITLE
prefetch

### ISSUE THREAD

**Issue by kdhzoot** [EMDC-OS/remote-swap#2]
How is the prefetch percentage determined?

**Comment by tlsghkrnfla** [comment]
To avoid bottlenecks caused by network faults while the application switches and prefetches data from the edge, it is crucial to carefully define the boundary between data to be processed locally and data to be fetched from the edge, based on the accessed pages during the switch. When the number of page faults during the application switch is low, less data should be prefetched, whereas a higher number of page faults allows for more data to be prefetched.
